server:
  port: 8765

spring:
  application:
    name: Consumer

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true